deployments:
  MyApp:
    filename:
      ./docker/Dockerfile
    context_path:
      ./
    port_forwarding:
      # For this example the user's application HTTP service is
      # listening to port 3000. We are mapping to port 80 in the
      # actual host VM so Squash can route traffic to the application.
      80:3000
